# Importing Libraries

In [22]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier, XGBRegressor
from lightgbm import LGBMClassifier, LGBMRegressor
from sklearn.ensemble import VotingRegressor
from sklearn.model_selection import train_test_split
from sklearn.base import clone
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, f1_score, mean_absolute_error
import joblib

In [23]:
df = pd.read_csv('dataset.csv')
df.head()

,student_id,cgpa,academic_backlogs,internships,internship_quality,certifications,projects,communication_skills,extra_curricular,college_tier,...,region,year,placed_3m,placed_6m,placed_12m,salary_lpa,delayed_placement_risk,loan_amount,emi_monthly,income_coverage_ratio
0,STUD_00001,8.10,0,1,none,0,4,8.2,0,2,...,North,2023,0,1,1,9.37,0,1340000.0,18454.0,10.0
1,STUD_00002,7.33,1,1,medium,0,2,7.1,2,2,...,South,2024,1,1,1,7.45,0,1161000.0,25250.0,10.0
2,STUD_00003,8.28,2,1,low,7,3,8.4,4,1,...,North,2023,1,1,1,10.35,0,2149000.0,46723.0,10.0
3,STUD_00004,9.33,0,3,none,2,8,9.9,2,2,...,East,2023,1,1,1,9.12,0,1708000.0,37133.0,10.0
4,STUD_00005,7.22,0,0,none,5,1,7.4,2,2,...,North,2025,1,0,1,8.40,0,1568000.0,21597.0,10.0

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   student_id              10000 non-null  object
 1   cgpa                    10000 non-null  float64
 2   academic_backlogs       10000 non-null  int64
 3   internships             10000 non-null  int64
 4   internship_quality      10000 non-null  object
 5   certifications          10000 non-null  int64
 6   projects                10000 non-null  int64
 7   communication_skills    10000 non-null  float64
 8   extra_curricular        10000 non-null  int64
 9   college_tier            10000 non-null  int64
 10  branch                  10000 non-null  object
 11  placement_rate          10000 non-null  float64
 12  market_demand           10000 non-null  object
 13  region                  10000 non-null  object
 14  year                    10000 non-null  int64
 15  placed_3m               10000 non-null  int64
 16  placed_6m               10000 non-null  int64
 17  placed_12m              10000 non-null  int64
 18  salary_lpa              10000 non-null  float64
 19  delayed_placement_risk  10000 non-null  int64
 20  loan_amount             10000 non-null  float64
 21  emi_monthly             10000 non-null  float64
 22  income_coverage_ratio   10000 non-null  float64
dtypes: float64(7), int64(11), object(5)
memory usage: 1.8+ MB

In [25]:
df.describe()

,cgpa,academic_backlogs,internships,certifications,projects,communication_skills,extra_curricular,college_tier,placement_rate,year,placed_3m,placed_6m,placed_12m,salary_lpa,delayed_placement_risk,loan_amount,emi_monthly,income_coverage_ratio
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,1.000000e+04,10000.000000,10000.0
mean,7.489669,0.675300,1.048800,2.045900,3.049200,6.978280,1.637800,2.098100,0.640116,2024.512200,0.44410,0.786500,0.921400,8.899477,0.061200,1.795615e+06,31516.634300,10.0
std,1.181367,0.884052,1.014456,1.430314,1.739794,1.479921,1.234732,0.697657,0.086335,1.122665,0.49689,0.409798,0.269127,1.486789,0.239709,5.938718e+05,12054.265755,0.0
min,4.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,1.000000,0.378000,2023.000000,0.00000,0.000000,0.000000,3.000000,0.000000,5.000000e+05,6888.000000,10.0
25%,6.690000,0.000000,0.000000,1.000000,2.000000,6.000000,1.000000,2.000000,0.577000,2024.000000,0.00000,1.000000,1.000000,7.900000,0.000000,1.388000e+06,23081.000000,10.0
50%,7.500000,0.000000,1.000000,2.000000,3.000000,7.000000,1.000000,2.000000,0.640000,2025.000000,0.00000,1.000000,1.000000,8.885000,0.000000,1.794000e+06,30562.500000,10.0
75%,8.310000,1.000000,2.000000,3.000000,4.000000,8.000000,2.000000,3.000000,0.700000,2026.000000,1.00000,1.000000,1.000000,9.930000,0.000000,2.199000e+06,39012.000000,10.0
max,10.000000,6.000000,5.000000,8.000000,10.000000,10.000000,4.000000,3.000000,0.915000,2026.000000,1.00000,1.000000,1.000000,14.300000,1.000000,3.939000e+06,85636.000000,10.0

In [26]:
df.columns.value_counts()

student_id                1
cgpa                      1
academic_backlogs         1
internships               1
internship_quality        1
certifications            1
projects                  1
communication_skills      1
extra_curricular          1
college_tier              1
branch                    1
placement_rate            1
market_demand             1
region                    1
year                      1
placed_3m                 1
placed_6m                 1
placed_12m                1
salary_lpa                1
delayed_placement_risk    1
loan_amount               1
emi_monthly               1
income_coverage_ratio     1
Name: count, dtype: int64

In [27]:
df.isnull().sum()

student_id                0
cgpa                      0
academic_backlogs         0
internships               0
internship_quality        0
certifications            0
projects                  0
communication_skills      0
extra_curricular          0
college_tier              0
branch                    0
placement_rate            0
market_demand             0
region                    0
year                      0
placed_3m                 0
placed_6m                 0
placed_12m                0
salary_lpa                0
delayed_placement_risk    0
loan_amount               0
emi_monthly               0
income_coverage_ratio     0
dtype: int64

# Feature Engineering

In [28]:
df = df.drop(columns=['student_id'], errors='ignore')

# 1. Success Score: Combining academic and communication excellence
df['Success_Score'] = (df['cgpa'] * df['communication_skills']) / (df['academic_backlogs'] + 1)

# 2. Portfolio Strength: Weighting projects and certifications heavily
df['Portfolio_Strength'] = (df['projects'] * 1.5) + (df['certifications'] * 1.2) + (df['internships'] * 2.0)

# 3. skill_depth: Combined skills total
df['skill_depth'] = df['communication_skills'] + df['certifications'] + df['projects']

print('M+ Sanitized Features engineered successfully.')
df.head()

M+ Sanitized Features engineered successfully.

,cgpa,academic_backlogs,internships,internship_quality,certifications,projects,communication_skills,extra_curricular,college_tier,branch,...,placed_6m,placed_12m,salary_lpa,delayed_placement_risk,loan_amount,emi_monthly,income_coverage_ratio,Success_Score,Portfolio_Strength,skill_depth
0,8.10,0,1,none,0,4,8.2,0,2,CSE,...,1,1,9.37,0,1340000.0,18454.0,10.0,66.4200,8.0,12.2
1,7.33,1,1,medium,0,2,7.1,2,2,CSE,...,1,1,7.45,0,1161000.0,25250.0,10.0,26.0215,5.0,9.1
2,8.28,2,1,low,7,3,8.4,4,1,CSE,...,1,1,10.35,0,2149000.0,46723.0,10.0,23.1840,14.9,18.4
3,9.33,0,3,none,2,8,9.9,2,2,CSE,...,1,1,9.12,0,1708000.0,37133.0,10.0,92.3670,20.4,19.9
4,7.22,0,0,none,5,1,7.4,2,2,ECE,...,0,1,8.40,0,1568000.0,21597.0,10.0,53.4280,7.5,13.4

In [29]:
df['skills'] = df['communication_skills'] + df['certifications'] + df['projects']

In [30]:
df = df[df['salary_lpa'] < df['salary_lpa'].quantile(0.95)]

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9497 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   cgpa                    9497 non-null   float64
 1   academic_backlogs       9497 non-null   int64
 2   internships             9497 non-null   int64
 3   internship_quality      9497 non-null   object
 4   certifications          9497 non-null   int64
 5   projects                9497 non-null   int64
 6   communication_skills    9497 non-null   float64
 7   extra_curricular        9497 non-null   int64
 8   college_tier            9497 non-null   int64
 9   branch                  9497 non-null   object
 10  placement_rate          9497 non-null   float64
 11  market_demand           9497 non-null   object
 12  region                  9497 non-null   object
 13  year                    9497 non-null   int64
 14  placed_3m               9497 non-null   int64
 15  placed_6m               9497 non-null   int64
 16  placed_12m              9497 non-null   int64
 17  salary_lpa              9497 non-null   float64
 18  delayed_placement_risk  9497 non-null   int64
 19  loan_amount             9497 non-null   float64
 20  emi_monthly             9497 non-null   float64
 21  income_coverage_ratio   9497 non-null   float64
 22  Success_Score           9497 non-null   float64
 23  Portfolio_Strength      9497 non-null   float64
 24  skill_depth             9497 non-null   float64
 25  skills                  9497 non-null   float64
dtypes: float64(11), int64(11), object(4)
memory usage: 2.0+ MB

# Feature transformation

In [32]:
df['placement_rate'].unique()

array([0.693, 0.606, 0.697, 0.638, 0.691, 0.592, 0.702, 0.468, 0.738,
       0.579, 0.42 , 0.668, 0.541, 0.48 , 0.624, 0.672, 0.532, 0.54 ,
       0.73 , 0.621, 0.62 , 0.519, 0.612, 0.499, 0.531, 0.518, 0.596,
       0.688, 0.812, 0.65 , 0.653, 0.615, 0.703, 0.737, 0.542, 0.767,
       0.656, 0.525, 0.574, 0.611, 0.677, 0.673, 0.607, 0.662, 0.762,
       0.622, 0.683, 0.646, 0.867, 0.502, 0.741, 0.613, 0.681, 0.8  ,
       0.546, 0.593, 0.512, 0.551, 0.509, 0.548, 0.552, 0.67 , 0.659,
       0.798, 0.701, 0.614, 0.719, 0.618, 0.679, 0.616, 0.547, 0.667,
       0.495, 0.636, 0.55 , 0.654, 0.713, 0.602, 0.68 , 0.625, 0.871,
       0.597, 0.524, 0.587, 0.682, 0.644, 0.771, 0.445, 0.378, 0.528,
       0.57 , 0.59 , 0.511, 0.66 , 0.754, 0.698, 0.725, 0.555, 0.627,
       0.486, 0.71 , 0.761, 0.589, 0.648, 0.489, 0.684, 0.566, 0.774,
       0.588, 0.685, 0.717, 0.832, 0.603, 0.569, 0.704, 0.573, 0.722,
       0.746, 0.56 , 0.726, 0.795, 0.619, 0.608, 0.601, 0.669, 0.626,
       0.674, 0.556, 0.554, 0.46 , 0.787, 0.692, 0.599, 0.724, 0.75 ,
       0.759, 0.598, 0.709, 0.58 , 0.641, 0.539, 0.664, 0.792, 0.577,
       0.649, 0.639, 0.63 , 0.536, 0.493, 0.756, 0.714, 0.568, 0.696,
       0.721, 0.694, 0.687, 0.676, 0.632, 0.609, 0.605, 0.643, 0.732,
       0.652, 0.581, 0.469, 0.61 , 0.727, 0.604, 0.578, 0.707, 0.557,
       0.572, 0.485, 0.663, 0.747, 0.594, 0.715, 0.829, 0.527, 0.855,
       0.533, 0.631, 0.473, 0.666, 0.76 , 0.586, 0.517, 0.437, 0.595,
       0.462, 0.635, 0.498, 0.466, 0.779, 0.623, 0.665, 0.545, 0.543,
       0.491, 0.575, 0.526, 0.565, 0.645, 0.567, 0.634, 0.752, 0.53 ,
       0.651, 0.783, 0.658, 0.833, 0.6  , 0.562, 0.561, 0.757, 0.637,
       0.51 , 0.753, 0.647, 0.772, 0.813, 0.507, 0.716, 0.744, 0.628,
       0.7  , 0.558, 0.817, 0.728, 0.735, 0.671, 0.523, 0.69 , 0.529,
       0.617, 0.769, 0.584, 0.859, 0.576, 0.723, 0.739, 0.822, 0.655,
       0.465, 0.699, 0.842, 0.765, 0.821, 0.515, 0.686, 0.564, 0.503,
       0.705, 0.629, 0.763, 0.504, 0.758, 0.773, 0.776, 0.78 , 0.782,
       0.426, 0.553, 0.544, 0.52 , 0.449, 0.535, 0.828, 0.474, 0.72 ,
       0.706, 0.406, 0.711, 0.775, 0.661, 0.825, 0.801, 0.731, 0.729,
       0.689, 0.501, 0.492, 0.549, 0.789, 0.736, 0.496, 0.764, 0.678,
       0.484, 0.454, 0.781, 0.64 , 0.802, 0.497, 0.809, 0.633, 0.74 ,
       0.591, 0.583, 0.563, 0.49 , 0.799, 0.708, 0.45 , 0.657, 0.853,
       0.742, 0.538, 0.482, 0.695, 0.5  , 0.748, 0.506, 0.851, 0.794,
       0.786, 0.508, 0.81 , 0.791, 0.814, 0.788, 0.582, 0.843, 0.494,
       0.559, 0.537, 0.534, 0.876, 0.443, 0.796, 0.456, 0.571, 0.455,
       0.816, 0.585, 0.733, 0.866, 0.513, 0.418, 0.675, 0.768, 0.826,
       0.47 , 0.784, 0.516, 0.459, 0.805, 0.521, 0.831, 0.806, 0.718,
       0.522, 0.815, 0.79 , 0.793, 0.461, 0.811, 0.514, 0.766, 0.852,
       0.778, 0.712, 0.827, 0.743, 0.431, 0.467, 0.405, 0.82 , 0.428,
       0.749, 0.804, 0.487, 0.472, 0.425, 0.488, 0.387, 0.483, 0.854,
       0.751, 0.464, 0.642, 0.475, 0.808, 0.777, 0.435, 0.457, 0.77 ,
       0.745, 0.797, 0.441, 0.824, 0.452, 0.823, 0.478, 0.471, 0.785,
       0.505, 0.463, 0.433, 0.453, 0.427, 0.479, 0.481, 0.868, 0.901,
       0.841, 0.863, 0.734, 0.442, 0.892, 0.432, 0.885, 0.755, 0.84 ,
       0.807, 0.446, 0.436, 0.451, 0.844, 0.448, 0.839, 0.834, 0.476,
       0.818, 0.838, 0.477, 0.439, 0.434, 0.879, 0.424, 0.447, 0.803,
       0.85 , 0.819, 0.429, 0.9  , 0.835, 0.423, 0.379, 0.857, 0.847,
       0.896, 0.416, 0.417, 0.864, 0.915, 0.848, 0.889, 0.858, 0.458,
       0.83 , 0.44 , 0.849, 0.438, 0.86 , 0.845, 0.856, 0.444, 0.4  ,
       0.88 , 0.836, 0.877, 0.39 , 0.91 , 0.846, 0.862])

In [33]:
exclude = ['placed_3m', 'placed_6m', 'placed_12m', 'salary_lpa', 'placement_rate']
num_cols = [c for c in df.drop(columns=exclude).columns if c not in ['branch', 'region', 'internship_quality', 'market_demand']]
print(f'Final Training Features Count: {len(num_cols) + 4}')

Final Training Features Count: 21

In [34]:
ct = ColumnTransformer(transformers = [('num', StandardScaler(), num_cols),
                                       ('ohe', OneHotEncoder(drop = 'first', sparse_output = False, handle_unknown = 'ignore'), ['branch', 'region']),
                                       ('oe', OrdinalEncoder(categories = [['none', 'low', 'medium', 'high'],['low','medium','high']]), ['internship_quality', 'market_demand'])
    
])

# Pipelines

## i. Classification pipeline

In [35]:
clf_pipe = Pipeline([('ct', ct),
                     ('model', XGBClassifier(n_estimators = 100))])

## ii. Regression pipeline

In [36]:
xgb_reg = XGBRegressor(n_estimators=1000, learning_rate=0.01, max_depth=6, subsample=0.8, colsample_bytree=0.8, random_state=42)
lgbm_reg = LGBMRegressor(n_estimators=1000, learning_rate=0.01, max_depth=6, subsample=0.8, importance_type='gain', random_state=42, verbose=-1)

reg_ensemble = VotingRegressor([('xgb', xgb_reg), ('lgbm', lgbm_reg)])
reg_pipe = Pipeline([('ct', ct), ('model', reg_ensemble)])
print('M+ Voting Ensemble Ready.')

M+ Voting Ensemble Ready.

# Splitting dataset

In [37]:
x = df.drop(columns=['placed_3m', 'placed_6m', 'placed_12m', 'salary_lpa', 'placement_rate'])
y = df[['placed_3m', 'placed_6m', 'placed_12m', 'salary_lpa', 'placement_rate']]
print('X Columns:', x.columns.tolist())
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

X Columns: ['cgpa', 'academic_backlogs', 'internships', 'internship_quality', 'certifications', 'projects', 'communication_skills', 'extra_curricular', 'college_tier', 'branch', 'market_demand', 'region', 'year', 'delayed_placement_risk', 'loan_amount', 'emi_monthly', 'income_coverage_ratio', 'Success_Score', 'Portfolio_Strength', 'skill_depth', 'skills']

In [38]:
y_3m_train = y_train['placed_3m']
y_6m_train = y_train['placed_6m']
y_12m_train = y_train['placed_12m']
y_sal_train = y_train['salary_lpa']
y_placement_rate_train = y_train['placement_rate']

y_3m_test = y_test['placed_3m']
y_6m_test = y_test['placed_6m']
y_12m_test = y_test['placed_12m']
y_sal_test = y_test['salary_lpa']
y_placement_rate_test = y_test['placement_rate']

# Model training

In [39]:
model_3m = clone(clf_pipe)
model_6m = clone(clf_pipe)
model_12m = clone(clf_pipe)
model_sal = clone(reg_pipe)
model_p_rate = clone(reg_pipe)

In [40]:
model_3m.fit(x_train, y_3m_train)
model_6m.fit(x_train, y_6m_train)
model_12m.fit(x_train, y_12m_train)
model_sal.fit(x_train, y_sal_train)
model_p_rate.fit(x_train, y_placement_rate_train)

ValueError: The estimator XGBRegressor should be a regressor.

In [ ]:
y3m_pred = model_3m.predict(x_test)
y6m_pred = model_6m.predict(x_test)
y12m_pred = model_12m.predict(x_test)
y_sal_pred = model_sal.predict(x_test)
y_p_rate_pred = model_p_rate.predict(x_test)

c:\Users\MAYANK\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MAYANK\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

# Evaluating models

## classification models

In [ ]:
f1_score_y3 = f1_score(y3m_pred, y_3m_test)
f1_score_y6 = f1_score(y6m_pred, y_6m_test)
f1_score_y12 = f1_score(y12m_pred, y_12m_test)

acc_score_y3 = accuracy_score(y3m_pred, y_3m_test)
acc_score_y6 = accuracy_score(y6m_pred, y_6m_test)
acc_score_y12 = accuracy_score(y12m_pred, y_12m_test)

## regression models

In [ ]:
f1_score_y3 = f1_score(y_3m_test, y3m_pred)
f1_score_y6 = f1_score(y_6m_test, y6m_pred)
f1_score_y12 = f1_score(y_12m_test, y12m_pred)

acc_score_y3 = accuracy_score(y_3m_test, y3m_pred)
acc_score_y6 = accuracy_score(y_6m_test, y6m_pred)
acc_score_y12 = accuracy_score(y_12m_test, y12m_pred)

r2_sal = r2_score(y_sal_test, y_sal_pred)
r2_rate = r2_score(y_placement_rate_test, y_p_rate_pred)

mae_sal = mean_absolute_error(y_sal_test, y_sal_pred)
rmse_sal = np.sqrt(mean_squared_error(y_sal_test, y_sal_pred))
rmse_rate = np.sqrt(mean_squared_error(y_placement_rate_test, y_p_rate_pred))

print(f'Salary R2: {r2_sal:.4f} | R2 Rate: {r2_rate:.4f}')

Salary R2: 0.4211 | R2 Rate: 0.6335

In [ ]:
performance_c = pd.DataFrame({'F1 Score' : [f1_score_y3, f1_score_y6, f1_score_y12], 'Accuracy Score' : [acc_score_y3, acc_score_y6, acc_score_y12]}, 
                            index = ['y_3m', 'y_6m', 'y_12m'])
performance_c

       F1 Score  Accuracy Score
y_3m   0.509609        0.583684
y_6m   0.858029        0.758947
y_12m  0.951671        0.907895

In [ ]:
performance_r = pd.DataFrame({'R2 Score' : [r2_sal, r2_rate], 'RMSE Score' : [rmse_sal, rmse_rate]},
                            index = ['y_salary', 'y_placement_rate'])
performance_r

                  R2 Score  RMSE Score
y_salary          0.421078    1.030254
y_placement_rate  0.633521    0.051419

In [ ]:
models = [model_3m, model_6m, model_12m, model_sal, model_p_rate] # Bundling all 5 intelligence models for PRAGYA
joblib.dump(models, 'models.pkl')

['models.pkl']

In [ ]:
df.corr(numeric_only=True)['salary_lpa'].sort_values(ascending=False)

salary_lpa                1.000000
placement_rate            0.403646
internships               0.193533
cgpa                      0.169969
Portfolio_Strength        0.112521
Success_Score             0.105051
placed_3m                 0.082682
placed_12m                0.070823
placed_6m                 0.066953
year                      0.025430
communication_skills      0.023511
skills                    0.022325
skill_depth               0.022325
certifications            0.013148
extra_curricular          0.007829
loan_amount               0.004684
projects                  0.003891
emi_monthly              -0.016446
academic_backlogs        -0.074347
college_tier             -0.446455
delayed_placement_risk   -0.479572
income_coverage_ratio          NaN
Name: salary_lpa, dtype: float64